wfb/wfb/urls.py
from django.contrib import admin
from django.urls import path

from wfb_app.views import Index, List, Calc, AddUnitView, EditUnitView, RankingList, \
    LoginView, LogoutView, UsersList, CreateUserView, EditUserView, AddGameResultView, DeleteUser, UserDetailsView, \
    ArmyListView, ArmyDetailsView, DeleteUnitView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name="main"),


    path("add_unit/", AddUnitView.as_view(), name="add-unit"),
    path('units_list/', List.as_view(), name="units-list"),
    path('edit_unit/<int:id>/', EditUnitView.as_view(), name="edit-unit"),
    path("delete_unit/<int:id>/", DeleteUnitView.as_view()),
    path("army_list/", ArmyListView.as_view()),
    path("army_details/<int:id>/", ArmyDetailsView.as_view()),
    path('calculator/', Calc.as_view(), name="calc-view"),

    path("ranking/", RankingList.as_view(), name="ranking-list"),
    path("ranking/add_result/", AddGameResultView.as_view()),

    path("accounts/login/", LoginView.as_view()),
    path("logout/", LogoutView.as_view(), name="logout-user"),
    path("users/", UsersList.as_view(), name="users-list"),
    path("add_user/", CreateUserView.as_view()),
    path("edit_user/<int:id>/", EditUserView.as_view()),
    path("user_details/<int:id>/", UserDetailsView.as_view(), name="user-details"),
    path("users/delete/<int:id>/", DeleteUser.as_view()),


]

wfb/wfb_app/models.py
from django.db import models
from django.contrib.auth.models import User


ARMIES_CHOICE = (
    ("BH", "Beast Herds"),
    ("DL", "Demonic Legion"),
    ("DE", "Dread Elves"),
    ("DH", "Dvarwen Holds"),
    ("EoS", "Empire of Sonnstahl"),
    ("HE", "Highborn Elves"),
    ("ID", "Infernal Dwarves"),
    ("KoE", "Kingdome of Equitaine"),
    ("OK", "Ogre Khans"),
    ("OG", "Orcs and Goblins"),
    ("SA", "Saurian Ancients"),
    ("SE", "Sylvan Elves"),
    ("UD", "Undying Dynasties"),
    ("VC", "Vampire Covenant"),
    ("VS", "Vermin Swarm"),
    ("WDG", "Warriors of the Dark Gods")
)

GAME_RANK = (
    ("master", "Master"),
    ("local", "Local"),
    ("home", "Home")
)

OBJ = (
    ("1", "Hold the Ground"),
    ("2", "Breakthrough"),
    ("3", "Spoils of War"),
    ("4", "King of the Hill"),
    ("5", "Capture the Flag"),
    ("6", "Secure Target")
)


class Armys(models.Model):
    name = models.CharField(max_length=32)
    short_name = models.CharField(max_length=16)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Units(models.Model):
    name = models.CharField(max_length=64, unique=True)
    offensive = models.IntegerField()
    strength = models.IntegerField()
    ap = models.IntegerField()
    reflex = models.BooleanField(default=False)
    army = models.ForeignKey(Armys, on_delete=models.CASCADE, default=1)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_army = models.CharField(max_length=32, choices=ARMIES_CHOICE)


class GameResults(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    battle_points = models.IntegerField()
    objective = models.BooleanField(default=False)
    objective_type = models.CharField(max_length=32, choices=OBJ, blank=True)
    game_rank = models.CharField(max_length=16, choices=GAME_RANK)
    opponent = models.CharField(max_length=64)
    date = models.DateField(auto_now_add=True)



class Objectives(models.Model):
    name = models.CharField(max_length=32, choices=OBJ)

    def __str__(self):
        return self.name

wfb/wfb_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from .models import Units, Profile, GameResults


class AddUnit(forms.ModelForm):
    class Meta:
        model = Units
        fields = "__all__"
        labels = {
            "name": "Nazwa",
            "offensive": "Offensive Skill",
            "strength": "Siła",
            "ap": "Armour Piercing",
            "reflex": "Czy ma Lightning Reflexes",
            "armys": "Armia"
        }


class LogForm(forms.Form):
    login = forms.CharField(max_length=64, label="Login")
    password = forms.CharField(max_length=64, label="Haslo", widget=forms.PasswordInput)


class RegisterUserForm(forms.ModelForm):
    password_2 = forms.CharField(widget=forms.PasswordInput, label="Powtórz hasło")
    class Meta:
        model = User
        fields = ["username", "password", "password_2", "email"]
        widgets = {"password": forms.PasswordInput}
        labels = {
            "username": "Nickname",
            "password": "Hasło",
            "email": "Podaj email"
        }
    # def clean(self):
    #     cleaned_data = super().clean()
    #     username = cleaned_data["username"]
    #     if User.objects.filter(username=username).exists():
    #         raise ValidationError("Login zajety")
    #     password = cleaned_data["password"]
    #     password_2 = cleaned_data["password_2"]
    #     if password != password_2:
    #         raise ValidationError("Hasla sie nie zgadzaja")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["user_army"]
        labels = {"user_army": "Wybierz Armie"}


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email"]
        labels = {
            "username": "Nickname",
            "email": "Podaj email"
        }


class GameResultsForm(forms.ModelForm):
    class Meta:
        model = GameResults
        fields = ["battle_points", "objective", "objective_type", "game_rank", "opponent"]
        labels = {
            "user": "Nick",
            "battle_points": "Punkty",
            "objective": "Czy Objective wykonany",
            "objective_type": "Jaki Objective",
            "game_rank": "Ranga turnieju",
            "opponent": "Przeciwnik",
            "date": "Data"
        }

wfb/wfb_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import FormView, ListView

from functions import towound, afterarmour
from wfb_app.forms import AddUnit, LogForm, RegisterUserForm, ProfileForm, EditUserForm, GameResultsForm
from wfb_app.models import Units, Armys, GameResults, Objectives, Profile
from django.contrib.auth.models import User


class Index(View):
    # strona główna, 5ciu najleprzysz graczy, logowanie, linki
    def get(self, request):
        result = []
        users = User.objects.all()
        no_of_games = GameResults.objects.all().count()
        for user in users:
            games = GameResults.objects.filter(user=user)
            total = 0
            for game in games:
                total += game.battle_points
            #  user.id bo przy sortowaniu tych samych wynikow python nie ogarnia :)
            result.append([total, user.id, user])
        result.sort(reverse=True)
        result = result[:5]
        ctx = {"no_of_users": users.count(), "no_of_games": no_of_games, "result": result}
        return render(request, "index.html", ctx)


class Calc(LoginRequiredMixin, View):
    # Funkcjionalnosc Kalkulator, wylicza statystyke walki przy podanych parametrach przez uzytkownika
    # tylko dla zalogowanych
    def get(self, request):
        units_list = Units.objects.all()
        return render(request, "calculator.html", {"units_list": units_list})
    def post(self, request):
        unit_id = request.POST.get('name')
        attacks = int(request.POST.get('attacks'))
        defensive = int(request.POST.get('defensive'))
        resistance = int(request.POST.get('resistance'))
        if request.POST.get('option') == "fight":
            unit = Units.objects.get(pk=unit_id)
            if unit.reflex:
                ref = 1 / 6
            else:
                ref = 0
            if unit.offensive - defensive >= 4:
                x = 5 / 6
            elif 4 > unit.offensive - defensive >= 0:
                x = 2 / 3
            elif unit.offensive - defensive <= -4:
                x = 1 / 3
            else:
                x = 1 / 2
            hit = attacks * (x + ref)
            if x + ref == 1:
                hit = attacks * x
            wounds = towound(hit, unit.strength, resistance)
            saves = ["none", "6+", "5+", "4+", "3+", "2+", "1+"]
            arm = []
            for armour in range(0, 7):
                wounds_after_armour = afterarmour(unit.ap, armour, wounds)
                arm.append(wounds_after_armour)
            ctx = {
                    "hit": round(hit, 2),
                    "wounds": round(wounds, 2),
                    "arm": arm,
                    "saves": saves,
                    "unit": unit
                }
            return render(request, "calculator.html", ctx)


class List(LoginRequiredMixin, View):
    # Lista wszystkich oddzialow, nie zaleznie od armii
    # tylko dla zalogowanych
    def get(self, request):
        units_list = Units.objects.all().order_by("name")
        return render(request, "units_list.html", {"units_list": units_list})


class AddUnitView(LoginRequiredMixin, View):
    # dodanawnie nowej jednostki do DB
    # tylko dla zalogowanych
    def get(self, request):
        form = AddUnit()
        ctx = {"form": form}
        return render(request, "add_unit.html", ctx)
    def post(self, request):
        form = AddUnit(request.POST)
        if form.is_valid():
            form.save()
            return redirect("calc-view")


class EditUnitView(LoginRequiredMixin, View):
    # Edycja jednostki i zapis do DB
    # tylko dla zalogowanych
    def get(self, request, id):
        unit = Units.objects.get(pk=id)
        form = AddUnit(instance=unit)
        ctx = {"form": form}
        return render(request, "edit_unit.html", ctx)
    def post(self, request, id):
        unit = get_object_or_404(Units, pk=id)
        form = AddUnit(request.POST, instance=unit)
        if form.is_valid():
            form.save()
            return redirect("units-list")


class DeleteUnitView(LoginRequiredMixin, View):
    # Usuwanie jednostki z DB
    # tylko dla zalogowanych
    def get(self, request, id):
        unit = Units.objects.get(pk=id)
        unit.delete()
        return redirect("calc-view")


class ArmyListView(LoginRequiredMixin, View):
    # lista wszystkich dostepnych armii
    # linki do poszczegolnych jednostek armijnych
    # tylko dla zalogowanych
    def get(self, request):
        army_list = Armys.objects.all().order_by("name")
        return render(request, "army_list.html", {"army_list": army_list})


class ArmyDetailsView(LoginRequiredMixin, View):
    # szczegoly armii, wszystkie jednostki dodane dla danej armii
    # tylko dla zalogowanych
    def get(selfself, request, id):
        army = Armys.objects.get(pk=id)
        units = Units.objects.filter(army=army.id)
        ctx = {"army": army, "units": units}
        return render(request, "army_details.html", ctx)


class LoginView(FormView):
    # logowanie i authentykacja
    form_class = LogForm
    template_name = "login_form.html"
    success_url = "/"

    def form_valid(self, form):
        username = form.cleaned_data["login"]
        password = form.cleaned_data["password"]
        user = authenticate(self.request, username=username, password=password)
        if user:
            login(self.request, user)
            return super().form_valid(form)
        form.add_error(None, "Zły login lub haslo")
        return super().form_invalid(form)


class LogoutView(View):
    # wylogowanie
    def get(self, request):
        logout(request)
        return redirect("/")


class CreateUserView(View):
    # Rejestracja nowego uzytkownika
    def get(self, request):
        form = RegisterUserForm()
        profile_form = ProfileForm()
        ctx = {"form": form, "profile_form": profile_form}
        return render(request, "user_form.html", ctx)
    def post(self, request):
        form = RegisterUserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.set_password(form.cleaned_data["password"])
            user.save()
            user_army = profile_form.cleaned_data["user_army"]
            Profile.objects.create(
                user_army = user_army,
                user = user
            )
            return redirect("users-list")
        else:
            ctx = {"form": form, "profile_form": profile_form}
            return render(request, "user_form.html", ctx)


class EditUserView(LoginRequiredMixin, View):
    # edycja konta urzytkownika, email, armia
    def get(selfself, request, id):
        user = User.objects.get(pk=id)
        form = EditUserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
        return render(request, "user_form.html", {
            "form": form,
            "profile_form": profile_form
        })
    def post(self, request, id):
        user = User.objects.get(pk=id)
        form = EditUserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if form.is_valid() and profile_form.is_valid():
            form.save()
            profile_form.save()
            return redirect("users-list")


class UsersList(LoginRequiredMixin, ListView):
    # lista zarejestrowanych uzytkownikow
    # tylko dla zalogowanych
    model = User
    context_object_name = "users"
    ordering = "username"


class UserDetailsView(View):
    # Szczegoly uzytkownika, wszsytkie bitwy, punkty, armia
    def get(self, request, id):
        user = User.objects.get(pk=id)
        ranking = GameResults.objects.filter(user=user).order_by("-date")
        total = 0
        for score in ranking:
            total += score.battle_points
        ctx = {"ranking": ranking, "total": total, "user": user}
        return render(request, "user_details.html", ctx)


class DeleteUser(LoginRequiredMixin, View):
    # usuwanie uzytkownika
    # tylko dla mnie

    # musze zabezpieczyc jeszcze!!!!
    def get(self, request, id):
        user = User.objects.get(pk=id)
        user.delete()
        return redirect("users-list")


class RankingList(View):
    # Ranking wszsytkich uzytkownikow, z punktami
    # sortowanie po wynikach, rangze itd
    def get(self, request):
        ranking = GameResults.objects.all()
        return render(request, "ranking_list.html", {"ranking": ranking})
    def post(self, request):
        if request.POST.get("option") == "name_sort":
            ranking = GameResults.objects.all().order_by("user", "-battle_points")
            return render(request, "ranking_list.html", {"ranking": ranking})
        if request.POST.get("option") == "points_sort":
            ranking = GameResults.objects.all().order_by("-battle_points")
            return render(request, "ranking_list.html", {"ranking": ranking})
        if request.POST.get("option") == "rank_sort":
            ranking = GameResults.objects.all().order_by("-game_rank", "-date")
            return render(request, "ranking_list.html", {"ranking": ranking})
        else:
            ranking = GameResults.objects.all()
            return render(request, "ranking_list.html", {"ranking": ranking})


class AddGameResultView(LoginRequiredMixin, View):
    # dodawanie nowych wynikow do rankingu
    # tylko dla zalogowanych
    def get(self, request):
        form = GameResultsForm()
        ctx = {"form": form}
        return render(request, "ranking_form.html", ctx)
    def post(self, request):
        form = GameResultsForm(request.POST)
        if form.is_valid():
            result = form.save(commit=False)
            result.user = request.user
            result.save()

wfb/wfb_app/templates/__base__.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} | Aplikacja WFB</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <header class="page-header">
        <nav class="navbar navbar-expand-lg justify-content-between">
            <a href="/" class="navbar-brand main-logo main-logo-smaller">
                Aplikacja <span>WFB</span>
            </a>
         <div class="d-flex justify-content-around">
             <h4 class="text-light mr-3">Witaj Imię</h4>
         </div>
        </nav>
    </header>

    <section class="dashboard-section">
        <div class="row dashboard-nowrap">
                <ul class="nav flex-column long-bg">
                    <li class="nav-item">
                        <a class="nav-link" href="/">
                            <span>Pulpit</span>
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span>Lista graczy</span>
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <span>Dodaj gracza</span>
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/calculator/">
                            <span>Kalkulator</span>
                            <i class="fas fa-angle-right"></i>
                        </a>
                    </li>

<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="">-->
<!--                                <span>Edytuj dane</span>-->
<!--                                <i class="fas fa-angle-right"></i>-->
<!--                            </a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link disabled" href="">-->
<!--                                <span>Zmień hasło</span>-->
<!--                                <i class="fas fa-angle-right"></i>-->
<!--                            </a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="">-->
<!--                                <span>Użytkownicy</span>-->
<!--                                <i class="fas fa-angle-right"></i>-->
<!--                            </a>-->
<!--                        </li>-->

                    </ul>
            <div class="m-4 p-3 width-medium text-color-darker">

<!-- //--------------------------- page content -------------------------// -->
{% block content %}{% endblock content %}
<!-- //--------------------------- page content end ---------------------// -->

            </div>
        </div>
    </section>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

wfb/wfb_app/templates/add_unit.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
    <h1>Dodawanie Jednostek</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        <input class="btn btn-secondary rounded-1" type="submit" value="Dodaj">
        {% csrf_token %}
    </form>
<!--        <form action="" method="POST">-->
<!--            <label class="mt-4 ml-4 mr-4" for="name">Nazwa Jednostki</label>-->
<!--            <input class="p-1" type="text" id="name" name="name"><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="offensive">Offensive Skill:</label>-->
<!--            <input class="p-1" type="number" id="offensive" name="offensive" ><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="strength">Sila:</label>-->
<!--            <input class="p-1" type="number" id="strength" name="strength" ><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="ap">Armour Piercing:</label>-->
<!--            <input class="p-1" type="number" id="ap" name="ap" ><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="reflex">Czy ma Lightning Reflexes:</label>-->
<!--            <input class="p-1" type="checkbox" id="reflex" name="reflex" ><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="army">Wybierz armie:</label>-->
<!--            <select class="p-1" id="army" name="army">-->
<!--                {% for army in armys %}-->
<!--                <option class="btn btn-primary rounded-0" value="{{ army.id }}">{{ army.name }}</option>-->
<!--                {% endfor %}-->
<!--            </select>-->

<!--            <button class="btn btn-secondary rounded-1" type="submit" >Dodaj</button>-->
<!--        {% csrf_token %}-->
<!--        </form>-->
{% endblock content %}

wfb/wfb_app/templates/add_user.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
    <h1>Dodawanie Uzytkownika</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        <input class="btn btn-secondary rounded-1" type="submit" value="Dodaj">
        {% csrf_token %}
    </form>

{% endblock content %}

wfb/wfb_app/templates/army_details.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<h1>Szczegóły armii: {{ army.name }} ({{ army.short_name }})</h1>
    <div class="col-1">
        <div class="nav nav-pills nav-justified">
            <a class="nav-link active" href="/add_unit/">Dodaj</a>
        </div>
    </div>
        <table class="table border-bottom schedules-content">
            <tr>
                <th>Lista Jednostek</th>
                <th>Offensive</th>
                <th>Strength</th>
                <th>Ap</th>
                <th>Reflex</th>
                <th></th>
                <th></th>
            </tr>
            {% for unit in units %}
            <tr>
                <td>{{ unit.name }}</td>
                <td>{{ unit.offensive  }}</td>
                <td>{{ unit.strength  }}</td>
                <td>{{ unit.ap  }}</td>
                {% if unit.reflex %}
                    <td style="color: green">Tak</td>
                {% else %}
                    <td style="color: red">Nie</td>
                {% endif %}
                <td>
                    <button type="button" class="btn btn-primary rounded-1 pt-0 pb-0 pr-4 pl-4">
                        <a class="nav-link active" href="/edit_unit/{{ unit.id }}/">
                            <span>Edit</span>
                        </a>
                    </button>
                </td>
                <td>
                    <button type="button" class="btn btn-secondary rounded-1 pt-0 pb-0 pr-4 pl-4">
                        <a class="nav-link active" href="/delete_unit/{{ unit.id }}/">
                            <span>Delete</span>
                        </a>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </table>
<div class="row">
    <div class="col-2">
        <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="/calculator/">Back</a>
        </div>
    </div>
</div>

{% endblock %}

wfb/wfb_app/templates/army_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<h1>Lista</h1>

        <table class="table border-bottom schedules-content">
            <tr>
                <th>Nazwa Armii</th>
                <th>Skrot</th>
                <th>Opis</th>
            </tr>
            {% for army in army_list %}
            <tr>
                <td><a href="/army_details/{{ army.id }}/">{{ army.name }}</a></td>
                <td>{{ army.short_name }}</td>
                <td>{{ army.description }}</td>
            </tr>
            {% endfor %}
        </table>
<div class="row">
    <div class="col-2">
        <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="/">Back</a>
        </div>
    </div>
</div>


{% endblock content %}

wfb/wfb_app/templates/edit_unit.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
    <h1>Edytowanie Jednostek</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        <input class="btn btn-secondary rounded-1" type="submit" value="Edytuj">
        {% csrf_token %}
    </form>
<!--    <h1>Edytowanie Jednostek</h1>-->
<!--    {% if error %}-->
<!--    <h1>{{ error }}</h1>-->
<!--    {% else %}-->
<!--<h3>Nazwa jednostki: <span><b>{{ unit.name }}</b></span></h3>-->
<!--        <form action="" method="POST">-->
<!--            <label class="mt-4 ml-4 mr-4" for="offensive">Offensive Skill:</label>-->
<!--            <input class="p-1" type="number" id="offensive" name="offensive" min="1" value="{{ unit.offensive }}"><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="strength">Sila:</label>-->
<!--            <input class="p-1" type="number" id="strength" name="strength" min="1" value="{{ unit.strength }}"><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="ap">Armour Piercing:</label>-->
<!--            <input class="p-1" type="number" id="ap" name="ap" min="0" value="{{ unit.ap }}"><br>-->
<!--            <label class="mt-4 ml-4 mr-4" for="reflex">Czy ma Lightning Reflexes:</label>-->
<!--            <input class="p-1" type="checkbox" id="reflex" name="reflex" {% if unit.reflex == True %} checked {% endif %}"><br>-->

<!--            <button class="btn btn-secondary rounded-1" type="submit" >Zapisz</button>-->
<!--        {% csrf_token %}-->
<!--        </form>-->
<!--    {% endif %}-->
{% endblock content %}

wfb/wfb_app/templates/edit_user.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
    <h1>Edytowanie Uzytkownika</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        <input class="btn btn-secondary rounded-1" type="submit" value="Edytuj">
        {% csrf_token %}
    </form>

{% endblock content %}

wfb/wfb_app/templates/ranking_form.html
{% extends "base.html" %}
{% block content %}
<h2>Uzytkownik: {{ request.user.username }} ({{ request.user.profile.user_army }})</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">

    </form>
{% endblock %}

wfb/wfb_app/templates/ranking_list.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
<h1>Ranking</h1>
    <div class="col-1">
        {% if request.user.is_authenticated %}
        <div class="nav nav-pills nav-justified">
            <a class="nav-link active" href="/ranking/add_result/">Dodaj wynik</a>
        </div>
        {% endif %}
    </div>
        <table class="table border-bottom schedules-content">

            <tr>
                <td>
                    <form action="" method="POST">
                    <button class="btn btn-secondary rounded-1" type="submit" name="option" value="name_sort">Sortuj</button>
                    {% csrf_token %}
                    </form>
                </td>
                <td>
                    <form action="" method="POST">
                    <button class="btn btn-secondary rounded-1" type="submit" name="option" value="points_sort">Sortuj</button>
                    {% csrf_token %}
                    </form>
                </td>
                <td></td>
                <td></td>
                <td>
                    <form action="" method="POST">
                    <button class="btn btn-secondary rounded-1" type="submit" name="option" value="rank_sort">Sortuj</button>
                    {% csrf_token %}
                    </form>
                </td>
                <td></td>
                <td></td>
            </tr>

            <tr>
                <th>Nickname</th>
                <th>Punkty</th>
                <th>Czy wykonany objective</th>
                <th>Jaki Objective</th>
                <th>Ranga turnieju/gry</th>
                <th>Przeciwnik</th>
                <th>Data</th>
            </tr>
            {% for result in ranking %}
            <tr>
                <td><a href="/user_details/{{ result.user.id }}/">{{ result.user }}</a></td>
                <td>{{ result.battle_points }}</td>
                <td>{{ result.objective  }}</td>
                <td>{{ result.get_objective_type_display  }}</td>
                <td>{{ result.get_game_rank_display  }}</td>
                <td>{{ result.opponent  }}</td>
                <td>{{ result.date  }}</td>
            </tr>
            {% endfor %}
        </table>
<div class="row">
    <div class="col-2">
        <div class="nav flex-column nav-pills">
            <a class="nav-link active" href="/">Back</a>
        </div>
    </div>
</div>

{% endblock %}

wfb/wfb_app/templates/user_form.html
{% extends "base.html" %}
{% block content %}
<h2>User:</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Save">

    </form>
{% endblock %}